name: Cucumber CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: run cucumber test 🔧
        run: chmod +x gradlew && ./gradlew test
        continue-on-error: true
        
      - name: rename to index.html
        run: |
            if [-e build/cucumber-reports/cucumber-html-reports/overview-features.html] \
               then cp build/cucumber-reports/cucumber-html-reports/overview-features.html build/cucumber-reports/cucumber-html-reports/index.html \
            fi 

      - name: Get github branch
        run: echo ::set-output name=branch_name::${GITHUB_REF#refs/*/}
        id: gitref
        
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages 
          folder: build/cucumber-reports/cucumber-html-reports/ 
          target-folder: ${{ steps.gitref.outputs.branch_name }}/${{ github.run_number }}
